### General Properties

[layout]
autosize = false
width = 600                                                        # 6in @ 100dpi
height = 500                                                       # 5in @ 100dpi
paper_bgcolor = "#E6F5E6"
plot_bgcolor = "#CBD5DD"
colorway = ["#4472C4", "#ED7D31", "#548235", "#7030A0", "#CE34D1"]

[layout.font]
family = "Arial"
size = 14
color = "black"

[layout.margin]
l = 40
r = 40
b = 40
t = 0
pad = 0

### Scatter (Line) Behavior

[[data.scatter]]

[data.scatter.marker]
size = 10

[data.scatter.line]
width = 3
shape = "spline"

### Title

[layout.title]
automargin = false
x = 0.5
xanchor = "center"
y = 1
yanchor = "middle"

[layout.title.font]
family = "Arial"
size = 20
color = "black"

[layout.title.pad]
l = 0
r = 0
b = 0
t = 0

### X-Axis

[layout.xaxis]
automargin = false
gridcolor = "#c8c8c8"
linecolor = "black"
zerolinecolor = "black"
tickcolor = "black"
gridwidth = 1
linewidth = 1
zerolinewidth = 1
showgrid = false
showline = true
mirror = true
ticks = "outside"
tickwidth = 1

[layout.xaxis.title]
standoff = 16

[layout.xaxis.title.font]
family = "Arial"
size = 20
color = "black"

[layout.xaxis.minor]
showgrid = false
gridcolor = "black"
tickcolor = "black"
ticks = "inside"

### Y-Axis

[layout.yaxis]
automargin = false
gridcolor = "#ebebeb"
linecolor = "black"
zerolinecolor = "black"
tickcolor = "black"
gridwidth = 1
linewidth = 1
zerolinewidth = 1
showgrid = true
showline = true
mirror = true
ticks = "outside"
tickwidth = 1

[layout.yaxis.title]
standoff = 0

[layout.yaxis.title.font]
family = "Arial"
size = 20
color = "black"

[layout.yaxis.minor]
showgrid = false
tickcolor = "black"
ticks = "inside"

### Legend

[layout.legend]
# x = 0.05
y = 1.006
# xanchor = "center"
yanchor = "top"
bordercolor = "black"
borderwidth = 1
bgcolor = "white"
# itemsizing = "constant"

[layout.legend.font]
family = "Arial"
size = 14
color = "black"
